/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OfficerComplaintsRouteImport } from './routes/officer.complaints'
import { Route as OfficerAnalyticsRouteImport } from './routes/officer.analytics'
import { Route as CitizenTrackRouteImport } from './routes/citizen.track'
import { Route as CitizenRegisterRouteImport } from './routes/citizen.register'
import { Route as CitizenNotificationsRouteImport } from './routes/citizen.notifications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminEscalationRouteImport } from './routes/admin.escalation'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/officer/',
  path: '/officer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerComplaintsRoute = OfficerComplaintsRouteImport.update({
  id: '/officer/complaints',
  path: '/officer/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerAnalyticsRoute = OfficerAnalyticsRouteImport.update({
  id: '/officer/analytics',
  path: '/officer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenTrackRoute = CitizenTrackRouteImport.update({
  id: '/citizen/track',
  path: '/citizen/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRegisterRoute = CitizenRegisterRouteImport.update({
  id: '/citizen/register',
  path: '/citizen/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenNotificationsRoute = CitizenNotificationsRouteImport.update({
  id: '/citizen/notifications',
  path: '/citizen/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEscalationRoute = AdminEscalationRouteImport.update({
  id: '/admin/escalation',
  path: '/admin/escalation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/escalation': typeof AdminEscalationRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/citizen/track': typeof CitizenTrackRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/complaints': typeof OfficerComplaintsRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/escalation': typeof AdminEscalationRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/citizen/track': typeof CitizenTrackRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/complaints': typeof OfficerComplaintsRoute
  '/admin': typeof AdminIndexRoute
  '/officer': typeof OfficerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/escalation': typeof AdminEscalationRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/notifications': typeof CitizenNotificationsRoute
  '/citizen/register': typeof CitizenRegisterRoute
  '/citizen/track': typeof CitizenTrackRoute
  '/officer/analytics': typeof OfficerAnalyticsRoute
  '/officer/complaints': typeof OfficerComplaintsRoute
  '/admin/': typeof AdminIndexRoute
  '/officer/': typeof OfficerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/departments'
    | '/admin/escalation'
    | '/admin/users'
    | '/citizen/notifications'
    | '/citizen/register'
    | '/citizen/track'
    | '/officer/analytics'
    | '/officer/complaints'
    | '/admin/'
    | '/officer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/departments'
    | '/admin/escalation'
    | '/admin/users'
    | '/citizen/notifications'
    | '/citizen/register'
    | '/citizen/track'
    | '/officer/analytics'
    | '/officer/complaints'
    | '/admin'
    | '/officer'
  id:
    | '__root__'
    | '/'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/departments'
    | '/admin/escalation'
    | '/admin/users'
    | '/citizen/notifications'
    | '/citizen/register'
    | '/citizen/track'
    | '/officer/analytics'
    | '/officer/complaints'
    | '/admin/'
    | '/officer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminEscalationRoute: typeof AdminEscalationRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CitizenNotificationsRoute: typeof CitizenNotificationsRoute
  CitizenRegisterRoute: typeof CitizenRegisterRoute
  CitizenTrackRoute: typeof CitizenTrackRoute
  OfficerAnalyticsRoute: typeof OfficerAnalyticsRoute
  OfficerComplaintsRoute: typeof OfficerComplaintsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/': {
      id: '/officer/'
      path: '/officer'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/complaints': {
      id: '/officer/complaints'
      path: '/officer/complaints'
      fullPath: '/officer/complaints'
      preLoaderRoute: typeof OfficerComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/analytics': {
      id: '/officer/analytics'
      path: '/officer/analytics'
      fullPath: '/officer/analytics'
      preLoaderRoute: typeof OfficerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/track': {
      id: '/citizen/track'
      path: '/citizen/track'
      fullPath: '/citizen/track'
      preLoaderRoute: typeof CitizenTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/register': {
      id: '/citizen/register'
      path: '/citizen/register'
      fullPath: '/citizen/register'
      preLoaderRoute: typeof CitizenRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/notifications': {
      id: '/citizen/notifications'
      path: '/citizen/notifications'
      fullPath: '/citizen/notifications'
      preLoaderRoute: typeof CitizenNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/escalation': {
      id: '/admin/escalation'
      path: '/admin/escalation'
      fullPath: '/admin/escalation'
      preLoaderRoute: typeof AdminEscalationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminEscalationRoute: AdminEscalationRoute,
  AdminUsersRoute: AdminUsersRoute,
  CitizenNotificationsRoute: CitizenNotificationsRoute,
  CitizenRegisterRoute: CitizenRegisterRoute,
  CitizenTrackRoute: CitizenTrackRoute,
  OfficerAnalyticsRoute: OfficerAnalyticsRoute,
  OfficerComplaintsRoute: OfficerComplaintsRoute,
  AdminIndexRoute: AdminIndexRoute,
  OfficerIndexRoute: OfficerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
